# Vector Algebra Linear Regression - Manual Inplementation

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
data = pd.read_csv('house_prices_grad_desc.csv')
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000


In [3]:
features = ['LotFrontage', 'LotArea', 'TotalBsmtSF', 'GarageArea']
target = 'SalePrice'

In [4]:
for feature in features:
    data[feature] = data[feature].fillna(data[feature].mean())

In [5]:
X_raw = data[features].values
X_raw

array([[   65.,  8450.,   856.,   548.],
       [   80.,  9600.,  1262.,   460.],
       [   68., 11250.,   920.,   608.],
       ...,
       [   66.,  9042.,  1152.,   252.],
       [   68.,  9717.,  1078.,   240.],
       [   75.,  9937.,  1256.,   276.]], shape=(1460, 4))

In [6]:
Y = data[target].values
Y

array([208500, 181500, 223500, ..., 266500, 142125, 147500], shape=(1460,))

In [7]:
# Number of data point
m = len(Y)

In [8]:
ones_column = np.ones((m, 1))

In [9]:
X_matrix = np.append(ones_column, X_raw, axis = 1)
X_matrix

array([[1.000e+00, 6.500e+01, 8.450e+03, 8.560e+02, 5.480e+02],
       [1.000e+00, 8.000e+01, 9.600e+03, 1.262e+03, 4.600e+02],
       [1.000e+00, 6.800e+01, 1.125e+04, 9.200e+02, 6.080e+02],
       ...,
       [1.000e+00, 6.600e+01, 9.042e+03, 1.152e+03, 2.520e+02],
       [1.000e+00, 6.800e+01, 9.717e+03, 1.078e+03, 2.400e+02],
       [1.000e+00, 7.500e+01, 9.937e+03, 1.256e+03, 2.760e+02]],
      shape=(1460, 5))

## Matrix Calculations
## $X^t$

In [10]:
X_t = X_matrix.T
X_t

array([[1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [6.500e+01, 8.000e+01, 6.800e+01, ..., 6.600e+01, 6.800e+01,
        7.500e+01],
       [8.450e+03, 9.600e+03, 1.125e+04, ..., 9.042e+03, 9.717e+03,
        9.937e+03],
       [8.560e+02, 1.262e+03, 9.200e+02, ..., 1.152e+03, 1.078e+03,
        1.256e+03],
       [5.480e+02, 4.600e+02, 6.080e+02, ..., 2.520e+02, 2.400e+02,
        2.760e+02]], shape=(5, 1460))

## $X^tX$

In [11]:
X_t_X = np.dot(X_t, X_matrix)
X_t_X

array([[1.46000000e+03, 1.02272939e+05, 1.53545690e+07, 1.54384700e+06,
        6.90551000e+05],
       [1.02272939e+05, 7.87191414e+06, 1.17398469e+09, 1.13268650e+08,
        5.05966981e+07],
       [1.53545690e+07, 1.17398469e+09, 3.06835185e+11, 1.79027631e+10,
        7.82410247e+09],
       [1.54384700e+06, 1.13268650e+08, 1.79027631e+10, 1.91331187e+09,
        7.96809277e+08],
       [6.90551000e+05, 5.05966981e+07, 7.82410247e+09, 7.96809277e+08,
        3.93311459e+08]])

## $(X^tX)^{-1}$

In [12]:
X_t_X_inv = np.linalg.inv(X_t_X)
X_t_X_inv

array([[ 9.27140026e-03, -7.93121711e-05,  1.19819882e-08,
        -1.71827405e-06, -2.83249400e-06],
       [-7.93121711e-05,  1.77543424e-06, -8.51413105e-10,
        -1.96486318e-08, -3.24024519e-08],
       [ 1.19819882e-08, -8.51413105e-10,  7.82007426e-12,
        -2.88124633e-11, -8.70177120e-12],
       [-1.71827405e-06, -1.96486318e-08, -2.88124633e-11,
         5.08112691e-09, -4.17619575e-09],
       [-2.83249400e-06, -3.24024519e-08, -8.70177120e-12,
        -4.17619575e-09,  2.03176224e-08]])

## $X^tY$

In [13]:
X_t_Y = np.dot(X_t, Y)
X_t_Y

array([2.64144946e+08, 1.93582539e+10, 3.08320594e+12, 3.10514510e+11,
       1.40384813e+11])

## w = $(X^tX)^{-1}X^tY$

In [14]:
w = np.dot(X_t_X_inv, X_t_Y)
w

array([1.94031519e+04, 1.44318186e+02, 6.25725539e-01, 6.84178046e+01,
       1.53243035e+02])

In [15]:
print("\nCalculation Complete!")
print("-" * 50)
print(f"Exact Bias (w_0)        : {w[0]:.2f}")
for j in range(len(features)):
    print(f"Exact Weight {features[j]} : {w[j+1]:.5f}")


Calculation Complete!
--------------------------------------------------
Exact Bias (w_0)        : 19403.15
Exact Weight LotFrontage : 144.31819
Exact Weight LotArea : 0.62573
Exact Weight TotalBsmtSF : 68.41780
Exact Weight GarageArea : 153.24303


# Prediction:
$Y = w^t x$

In [16]:
test_data = np.array([80, 9500, 1500, 700])

test_data_with_bias = np.insert(test_data, 0, 1)

w_t = w.T

exact_prediction = np.dot(w_t, test_data_with_bias)

print(f"\nNormal Equation Prediction: ${exact_prediction:,.2f}")


Normal Equation Prediction: $246,789.83
